sudo: false
language: ruby
branches:
  only:
    - master
rvm:
  - 2.3.3
  - 2.4.3
  - 2.5.0
  - ruby-head

script:
  - bundle exec rake style:chefstyle
  - bundle exec rake unit
  - bundle exec rake yard

matrix:
  allow_failures:
  - rvm: 2.3.3
